name: CI

on:
  push:
    branches:
    - action
    tags:
    - '*'

jobs:
  build_and_release:
    name: template
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          target: x86_64-unknown-linux-musl

      - name: Build
        run: >
          sudo bash -c 'apt update && apt install upx binutils -y';
          rustup component add rust-src --toolchain nightly;
          cargo build --release;
          strip -s -R .comment -R .gnu.version --strip-unneeded target/x86_64-unknown-linux-musl/release/template;
          upx -9 --best target/x86_64-unknown-linux-musl/release/template -o target/x86_64-unknown-linux-musl/release/template-upx;

      - name: Build archlinux package
        uses: countstarlight/arch-makepkg-action@master
        with:
          scripts: "cp target/x86_64-unknown-linux-musl/release/{template,template-upx} . && makepkg"

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: template*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
